### ISSUE TITLE
onos-config restrats after a long time due to a panic 

### ISSUE THREAD

**Issue by adibrastegarnia** [onosproject/onos-config#1188]
**Describe the bug**
If you run onos-config for a long time, you will see onos-config will be restrated because of the following panic:

```
panic: close of closed channel

goroutine 195 [running]:
github.com/onosproject/onos-config/pkg/store/snapshot/device.(*atomixStore).Watch.func1(0xc00021ff20, 0xc00057a2a0)
	/go/src/github.com/onosproject/onos-config/pkg/store/snapshot/device/store.go:287 +0x29b
created by github.com/onosproject/onos-config/pkg/store/snapshot/device.(*atomixStore).Watch
	/go/src/github.com/onosproject/onos-config/pkg/store/snapshot/device/store.go:259 +0x177

```

**To Reproduce**
Run one of the integration tests (e.g  TestDeviceState) and keep it running for a long time (hours)

**Expected behavior**
No panic error when you run onos-config for a long time.

**Comment by adibrastegarnia** [comment]
I had an instance of onos-config running for a long time and as you can see it is restarted 4 times:

```
kubectl get pods -n micro-onos -w
NAME                                                       READY   STATUS    RESTARTS   AGE
atomix-controller-dc74bf97-zkl95                           1/1     Running   0          17h
onos-cli-57966dfcb5-k5bm6                                  1/1     Running   0          16h
onos-config-7cd74f966-7crj5                                1/1     Running   4          10h
onos-config-config-db-1-0                                  1/1     Running   0          10h
onos-topo-9bccf8cc7-n47sr                                  1/1     Running   0          16h
onos-topo-config-db-1-0                                    1/1     Running   0          16h
raft-controller-raft-storage-controller-5d5f76d77f-krh74   1/1     Running   0          17h
```
