### ISSUE TITLE
Calling `onos config snapshot devicesim-1` causes onos-config to crash

### ISSUE THREAD

**Issue by SeanCondon** [onosproject/onos-config#864]
**Describe the bug**
On a newly installed system on `onit` with a few network changes and no snapshots, when I call
`onos config snapshot devicesim-1`
it causes onos-config to crash

**To Reproduce**
1. Create a cluster with `onit`
```bash
onit create cluster --set onos-cli.enabled=true
```
2. create a simulator `devicesim-1`:
```bash
onit -c onos add simulator -n devicesim-1
```
3. Run the snapshot command to retrieve snapshots
`onos config snapshot devicesim-1`

4. Observe that this command crashes onow config.
a) the reply is 
```bash
rpc error: code = Unavailable desc = transport is closing
```
b) kubectl shows that onos has restarted (see the restarts column):
```bash
Every 2.0s: kubectl get pods -n onos                                                                                                                       Z420: Fri Jan 10 10:02:09 2020

NAME                                 READY   STATUS    RESTARTS   AGE
atomix-controller-756f86cc9c-jjhhl   1/1     Running   0          15m
database-1-0                         1/1     Running   0          14m
devicesim-1                          1/1     Running   0          12m
devicesim-2                          1/1     Running   0          11m
onos-cli-8fddbd77f-c427r             1/1     Running   0          14m
onos-config-7f77c68c88-m7msc         1/1     Running   1          14m
onos-topo-58dbddcb64-rw8xc           1/1     Running   0          14m
```
c) onos-config stack trace below is produced

**Expected behavior**
I expected it to be able to handle the case where there are no snapshots on the system

**Logs, text or screenshots**
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x60 pc=0x10dd0d6]

goroutine 574 [running]:
github.com/onosproject/onos-config/api/types/snapshot/device.(*Snapshot).MarshalToSizedBuffer(0x0, 0x1e8a588, 0x0, 0x0, 0x87c803, 0x1237ea0, 0x1328a60)
	/go/src/github.com/onosproject/onos-config/api/types/snapshot/device/types.pb.go:522 +0x26
github.com/onosproject/onos-config/api/types/snapshot/device.(*Snapshot).Marshal(0x0, 0x1328a60, 0x0, 0x7f22a3ea28b8, 0x0, 0xc0020a6001)
	/go/src/github.com/onosproject/onos-config/api/types/snapshot/device/types.pb.go:505 +0x83
google.golang.org/grpc/encoding/proto.codec.Marshal(0x1328a60, 0x0, 0xc000402540, 0x14974c0, 0x87b3cc, 0xc000204000, 0x1248ba0)
	/go/src/github.com/onosproject/onos-config/vendor/google.golang.org/grpc/encoding/proto/proto.go:70 +0x194
google.golang.org/grpc.encode(0x7f22a8dcd3b0, 0x1e8a588, 0x1328a60, 0x0, 0x1e8a588, 0xc003d5b790, 0x11d2980, 0xc003d5b790, 0x11dc340)
	/go/src/github.com/onosproject/onos-config/vendor/google.golang.org/grpc/rpc_util.go:543 +0x52
google.golang.org/grpc.(*Server).sendResponse(0xc003768c00, 0x14a1a80, 0xc000afbe00, 0xc003c7a000, 0x1328a60, 0x0, 0x0, 0x0, 0xc003eb9388, 0x0, ...)
	/go/src/github.com/onosproject/onos-config/vendor/google.golang.org/grpc/server.go:845 +0x8b
google.golang.org/grpc.(*Server).processUnaryRPC(0xc003768c00, 0x14a1a80, 0xc000afbe00, 0xc003c7a000, 0xc00371ad50, 0x1e1cc58, 0x0, 0x0, 0x0)
	/go/src/github.com/onosproject/onos-config/vendor/google.golang.org/grpc/server.go:1042 +0x557
google.golang.org/grpc.(*Server).handleStream(0xc003768c00, 0x14a1a80, 0xc000afbe00, 0xc003c7a000, 0x0)
	/go/src/github.com/onosproject/onos-config/vendor/google.golang.org/grpc/server.go:1287 +0xda6
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc0037e2fe0, 0xc003768c00, 0x14a1a80, 0xc000afbe00, 0xc003c7a000)
	/go/src/github.com/onosproject/onos-config/vendor/google.golang.org/grpc/server.go:722 +0x9f
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/go/src/github.com/onosproject/onos-config/vendor/google.golang.org/grpc/server.go:720 +0xa1
```

**Additional context**

**Comment by SeanCondon** [comment]
this is still an issue
