### ISSUE TITLE
After calling `onos config compact-changes` onos-config crashes, and can't restart

### ISSUE THREAD

**Issue by SeanCondon** [onosproject/onos-config#865]
**Describe the bug**
When I run the command
`onos config compact-changes`
onos-config crashes, and can't restart

**To Reproduce**

- Set up a cluster with `onit create cluster` and create 2 simulators `devicesim-1` and `devicesim-2`
- Run the integration tests so that there will be a consistent set of changes populated in the system
- Then run the `commit-changes` command like above
- See how the command returns with `rpc error: code = Unavailable desc = transport is closing`
- See the list of active pods to see that the `onos-config` has **READY 0/1** and the status is `CrashLoopBackOff`

**Expected behavior**
I expect a `network snapshot` to be created for all network changes, with a corresponding set of `device snapshots`. I do not expect the system to crash

**Logs, text or screenshots**
Retrieving the log of the failed onos-config pod gives the following after startup:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x1082415]

goroutine 242 [running]:
github.com/onosproject/onos-config/pkg/controller/change/network.(*Reconciler).ensureDeviceRollbacks(0xc00016d5e0, 0xc00369e160, 0x0, 0x140e040, 0xc0036ae9c0)
	/go/src/github.com/onosproject/onos-config/pkg/controller/change/network/controller.go:335 +0xb5
github.com/onosproject/onos-config/pkg/controller/change/network.(*Reconciler).reconcileRollback(0xc00016d5e0, 0xc00369e160, 0xe, 0xc00369e160, 0x0)
	/go/src/github.com/onosproject/onos-config/pkg/controller/change/network/controller.go:309 +0x39
github.com/onosproject/onos-config/pkg/controller/change/network.(*Reconciler).Reconcile(0xc00016d5e0, 0xc0037a6090, 0xe, 0xc0037f8000, 0xc0037d5fb0, 0x1)
	/go/src/github.com/onosproject/onos-config/pkg/controller/change/network/controller.go:69 +0x9e
github.com/onosproject/onos-config/pkg/controller.(*Controller).reconcile(0xc000206240, 0xc0037a6090, 0xe, 0x13e9f00, 0xc00016d5e0, 0x1)
	/go/src/github.com/onosproject/onos-config/pkg/controller/controller.go:265 +0x71
github.com/onosproject/onos-config/pkg/controller.(*Controller).processRequests(0xc000206240, 0xc0037f8000)
	/go/src/github.com/onosproject/onos-config/pkg/controller/controller.go:247 +0xcd
created by github.com/onosproject/onos-config/pkg/controller.(*Controller).partition
	/go/src/github.com/onosproject/onos-config/pkg/controller/controller.go:227 +0x26d
```

**Additional context**
See also #864

**Comment by kuujo** [comment]
@SeanCondon I haven’t been able to reproduce this either with a test or manually, nor with a single node cluster or multiple nodes, not using the API or the CLI. The only thing I’ve found is that snapshots get stuck in the `MARK` phase when they are unable to remove any changes, which is certainly a bug.

**Comment by SeanCondon** [comment]
Thanks for looking at it. I will try one more time when i get back home tomorrow. If i can'r reproduce i will close the issue.

**Comment by kuujo** [comment]
Okay I will open issues for the bugs I did find.

**Comment by SeanCondon** [comment]
I can't reproduce

**Comment by SeanCondon** [comment]
I was able to reproduce this. It's important to run the integration test suite before calling `compact-changes`

The logs now say:

```
....
{"level":"info","ts":1573979802.3884037,"logger":"southbound.synchronizer","caller":"synchronizer/synchronizer.go:108","msg":"Syncing Op & State of devicesim-1 started. Mode 1"}
{"level":"info","ts":1573979802.388424,"logger":"southbound.synchronizer","caller":"synchronizer/synchronizer.go:393","msg":"Getting STATE partition for devicesim-1"}
{"level":"info","ts":1573979802.3922977,"logger":"southbound.synchronizer","caller":"synchronizer/synchronizer.go:393","msg":"Getting OPERATIONAL partition for devicesim-2"}
{"level":"info","ts":1573979802.3926969,"logger":"southbound.synchronizer","caller":"synchronizer/synchronizer.go:393","msg":"Getting OPERATIONAL partition for devicesim-1"}
{"level":"info","ts":1573979802.3939795,"logger":"manager","caller":"manager/devicehandler.go:59","msg":"Device devicesim-2 is updated with states REACHABLE, CONNECTED, AVAILABLE"}
{"level":"info","ts":1573979802.3940835,"logger":"manager","caller":"manager/devicehandler.go:24","msg":"Device devicesim-1 connected"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x10afd43]

goroutine 233 [running]:
github.com/onosproject/onos-config/pkg/controller/change/network.(*Reconciler).ensureDeviceRollbacks(0xc00000e820, 0xc0037ec420, 0x0, 0x144f160, 0xc003912300)
        /go/src/github.com/onosproject/onos-config/pkg/controller/change/network/controller.go:341 +0xc3
github.com/onosproject/onos-config/pkg/controller/change/network.(*Reconciler).reconcileRollback(0xc00000e820, 0xc0037ec420, 0xb, 0xc0037ec420, 0x0)
        /go/src/github.com/onosproject/onos-config/pkg/controller/change/network/controller.go:315 +0x39
github.com/onosproject/onos-config/pkg/controller/change/network.(*Reconciler).Reconcile(0xc00000e820, 0xc003661e60, 0xb, 0xc003882180, 0xc003915fb0, 0x1)
        /go/src/github.com/onosproject/onos-config/pkg/controller/change/network/controller.go:72 +0xb6
github.com/onosproject/onos-config/pkg/controller.(*Controller).reconcile(0xc0002a8630, 0xc003661e60, 0xb, 0x142a6e0, 0xc00000e820, 0x1)
        /go/src/github.com/onosproject/onos-config/pkg/controller/controller.go:267 +0x71
github.com/onosproject/onos-config/pkg/controller.(*Controller).processRequests(0xc0002a8630, 0xc003882180)
        /go/src/github.com/onosproject/onos-config/pkg/controller/controller.go:249 +0xcd
created by github.com/onosproject/onos-config/pkg/controller.(*Controller).partition
        /go/src/github.com/onosproject/onos-config/pkg/controller/controller.go:229 +0x26d
```

**Comment by ray-milkey** [comment]
I was able to reproduce this also.

**Comment by adibrastegarnia** [comment]
@SeanCondon @kuujo @ray-milkey 
This issue is not reproducible anymore (today Sep 8th, 2020) but we have another related issue that should be addressed (it is still valid) https://github.com/onosproject/onos-config/issues/899. if you reproduce this issue specifically, please open it again. Some part of the onos-config logs:

```
ceChanges for device moral-beetle
2020-09-08T21:38:25.707Z	INFO	controller/change/network	network/controller.go:73	Reconciling NetworkChange id:"nostalgic_kirch" index:12 revision:313 status:<state:COMPLETE incarnation:1 > created:<seconds:1599601046 nanos:901666600 > updated:<seconds:1599601105 nanos:396788700 > changes:<device_id:"learning-moth" device_version:"1.0.0" device_type:"Devicesim" values:<path:"/interfaces/interface[name=new-root]/config/name" value:<bytes:"new-root" type:STRING > > > refs:<device_change_id:"nostalgic_kirch:learning-moth:1.0.0" > deleted:true
2020-09-08T21:38:25.707Z	INFO	controller/change/device	device/controller.go:82	Reconciling DeviceChange <nil>
2020-09-08T21:38:25.706Z	INFO	controller/snapshot/device	device/controller.go:225	Completing DeviceSnapshot id:"0fe48d80-6c5c-4967-b0bb-f7ab9fd40f81:moral-beetle:1.0.0" device_id:"moral-beetle" device_version:"1.0.0" device_type:"Devicesim" revision:356 network_snapshot:<id:"0fe48d80-6c5c-4967-b0bb-f7ab9fd40f81" index:2 > max_network_change_index:18 status:<phase:DELETE state:COMPLETE > created:<seconds:1599601105 nanos:433892300 > updated:<seconds:1599601105 nanos:662798300 >
2020-09-08T21:38:25.705Z	INFO	controller/change/device	device/controller.go:82	Reconciling DeviceChange <nil>
2020-09-08T21:38:25.716Z	INFO	controller/change/network	network/controller.go:73	Reconciling NetworkChange id:"funny_borg" index:16 revision:316 status:<state:COMPLETE incarnation:1 > created:<seconds:1599601068 nanos:117083900 > updated:<seconds:1599601105 nanos:407971900 > changes:<device_id:"moral-beetle" device_version:"1.0.0" device_type:"Devicesim" values:<path:"/interfaces/interface[name=test]/config/name" value:<bytes:"test" type:STRING > > > refs:<device_change_id:"funny_borg:moral-beetle:1.0.0" > deleted:true
2020-09-08T21:38:25.720Z	INFO	controller/change/device	device/controller.go:82	Reconciling DeviceChange <nil>
2020-09-08T21:38:25.726Z	INFO	controller/change/network	network/controller.go:73	Reconciling NetworkChange id:"confident_bhabha" index:13 revision:314 status:<state:COMPLETE incarnation:1 > created:<seconds:1599601046 nanos:930963200 > updated:<seconds:1599601105 nanos:402589300 > changes:<device_id:"learning-moth" device_version:"1.0.0" device_type:"Devicesim" values:<path:"/interfaces/interface[name=new-root]/config/description" value:<bytes:"description" type:STRING > > values:<path:"/interfaces/interface[name=new-root]/config/enabled" value:<bytes:"\000" type:BOOL > > > refs:<device_change_id:"confident_bhabha:learning-moth:1.0.0" > deleted:true
2020-09-08T21:38:25.730Z	INFO	controller/snapshot/device	device/controller.go:221	Deleted 1 DeviceChanges for device rich-hamster
2020-09-08T21:38:25.730Z	INFO	controller/snapshot/device	device/controller.go:225	Completing DeviceSnapshot id:"0fe48d80-6c5c-4967-b0bb-f7ab9fd40f81:rich-hamster:1.0.0" device_id:"rich-hamster" device_version:"1.0.0" device_type:"Devicesim" revision:362 network_snapshot:<id:"0fe48d80-6c5c-4967-b0bb-f7ab9fd40f81" index:2 > max_network_change_index:5 status:<phase:DELETE state:COMPLETE > created:<seconds:1599601105 nanos:439639400 > updated:<seconds:1599601105 nanos:683356400 >
2020-09-08T21:38:25.731Z	INFO	controller/snapshot/device	device/controller.go:221	Deleted 1 DeviceChanges for device test-offline-device-1
2020-09-08T21:38:25.731Z	INFO	controller/snapshot/device	device/controller.go:225	Completing DeviceSnapshot id:"0fe48d80-6c5c-4967-b0bb-f7ab9fd40f81:test-offline-device-1:1.0.0" device_id:"test-offline-device-1" device_version:"1.0.0" device_type:"Devicesim" revision:366 network_snapshot:<id:"0fe48d80-6c5c-4967-b0bb-f7ab9fd40f81" index:2 > max_network_change_index:6 status:<phase:DELETE state:COMPLETE > created:<seconds:1599601105 nanos:445636200 > updated:<seconds:1599601105 nanos:700534200 >
2020-09-08T21:38:25.740Z	INFO	controller/change/network	network/controller.go:73	Reconciling NetworkChange id:"recursing_bohr" index:17 revision:317 status:<state:COMPLETE incarnation:1 > created:<seconds:1599601068 nanos:141921200 > updated:<seconds:1599601105 nanos:419587800 > changes:<device_id:"moral-beetle" device_version:"1.0.0" device_type:"Devicesim" values:<path:"/interfaces/interface[name=test]/config/enabled" value:<bytes:"\001" type:BOOL > > values:<path:"/interfaces/interface[name=test]/config/description" value:<bytes:"description" type:STRING > > > refs:<device_change_id:"recursing_bohr:moral-beetle:1.0.0" > deleted:true
2020-09-08T21:38:25.748Z	INFO	controller/change/network	network/controller.go:73	Reconciling NetworkChange id:"great_moore" index:14 revision:315 status:<state:COMPLETE incarnation:1 > created:<seconds:1599601046 nanos:999885600 > updated:<seconds:1599601105 nanos:405260000 > changes:<device_id:"learning-moth" device_version:"1.0.0" device_type:"Devicesim" values:<path:"/interfaces/interface[name=new-root]/config/enabled" value:<> removed:true > > refs:<device_change_id:"great_moore:learning-moth:1.0.0" > deleted:true
```
